# Generated by Django 4.0.6 on 2022-07-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacao', models.CharField(max_length=60)),
                ('horario', models.CharField(max_length=60)),
                ('duracao', models.IntegerField()),
                ('localidade', models.CharField(max_length=60)),
                ('localizacao', models.CharField(max_length=60)),
                ('accao', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.curso')),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
