# Generated by Django 4.0.6 on 2022-07-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_curso_modelo_remove_produto_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='descricao',
        ),
    ]
