# Generated by Django 4.0.6 on 2022-07-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_modelo_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formandos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('Habilitacoes', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('contacto', models.IntegerField()),
                ('morada', models.CharField(max_length=60)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('localidade', models.CharField(max_length=20)),
                ('bi', models.CharField(max_length=20)),
                ('validade', models.CharField(max_length=20)),
                ('data_nascimento', models.CharField(max_length=20)),
                ('natural', models.CharField(max_length=20)),
                ('nacionalidade', models.CharField(max_length=20)),
                ('nif', models.CharField(max_length=20)),
                ('observacoes', models.TextField()),
            ],
        ),
    ]
