# Generated by Django 4.0.6 on 2022-07-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_formandos'),
    ]

    operations = [
        migrations.AddField(
            model_name='formandos',
            name='modelos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='base.modelo'),
            preserve_default=False,
        ),
    ]
