# Generated by Django 4.0.6 on 2022-07-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_formandos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formandos',
            new_name='Formando',
        ),
    ]
