# Generated by Django 4.0.6 on 2022-07-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_formandos_formando'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formando',
            old_name='Habilitacoes',
            new_name='habilitacoes',
        ),
    ]
