# Generated by Django 4.0.6 on 2022-07-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_habilitacoes_formando_habilitacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='formacao',
            new_name='formador',
        ),
    ]
