# Generated by Django 4.0.6 on 2022-07-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_formacao_modelo_formador'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='formacao',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
