# Generated by Django 4.0.6 on 2022-07-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_curso_formacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='formacao',
        ),
        migrations.RemoveField(
            model_name='formando',
            name='modelo',
        ),
        migrations.AddField(
            model_name='curso',
            name='accao',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='duracao',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='horario',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='localidade',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='localizacao',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formando',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='base.curso'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Modelo',
        ),
        migrations.AddField(
            model_name='formador',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.curso'),
        ),
        migrations.AddField(
            model_name='formando',
            name='formador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='base.formador'),
            preserve_default=False,
        ),
    ]
