# Generated by Django 4.0.6 on 2022-07-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_formador_remove_curso_formacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formador', models.CharField(max_length=60)),
                ('horario', models.CharField(max_length=60)),
                ('duracao', models.IntegerField()),
                ('localidade', models.CharField(max_length=60)),
                ('localizacao', models.CharField(max_length=60)),
                ('accao', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='accao',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='duracao',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='localidade',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='formando',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='formando',
            name='formador',
        ),
        migrations.AddField(
            model_name='curso',
            name='formacao',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Formador',
        ),
        migrations.AddField(
            model_name='modelo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.curso'),
        ),
        migrations.AddField(
            model_name='formando',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='base.modelo'),
            preserve_default=False,
        ),
    ]
